meta_product_name: "Clairvoyance"
meta_title: "Clairvoyance - Meet Your Marketer"
meta_description: "We allow small business to match with experienced marketing agencies who can then offer a bid and proposal based on the information they've been provided."
meta_image: "og-image.png"                       # should exist in `app/assets/images/`
twitter_account: "@Clairvoyance_LeWagon"   # required for Twitter Cards
